name: edulearn
description: "EduLearn - Flutter + Firebase Learning App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI Icons
  cupertino_icons: ^1.0.8

  # ðŸ”¥ Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.3.0

  # ðŸ” Google Login
  google_sign_in: ^6.2.1

  # ðŸ“ Files (PDF / PPT)
  file_picker: ^8.1.2

  # ðŸŽ¥ Video
  video_player: ^2.9.1

  # âš¡ State Management / Navigation
  get: ^4.6.6
  shared_preferences: ^2.5.3
  youtube_player_flutter: ^9.1.3
  webview_flutter: ^4.13.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # ðŸ–¼ Assets
  assets:
    - assets/image/

  # ðŸ”¤ Fonts
  fonts:
    - family: FiraSans
      fonts:
        - asset: assets/font/FiraSans-Regular.ttf
        - asset: assets/font/FiraSans-Italic.ttf
          style: italic
        - asset: assets/font/FiraSans-Bold.ttf
          weight: 700
        - asset: assets/font/FiraSans-Black.ttf
          weight: 900

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/image/logowithbg.png"